### ISSUE TITLE
Replace `AppData\Roaming\Pub\Cache\bin` with `AppData\Local\Pub\Cache\bin` in PATH

### ISSUE THREAD

**Issue by julemand101** [dart-lang/chocolatey-packages#11]
Pub are no longer using the `Roaming` directory when handling cache and installation of programs. Instead, it have been using `Local` for some time:

https://github.com/dart-lang/pub/pull/2297
https://github.com/dart-lang/pub/pull/3831

The consequence of this is that installing Dart though Chocolatey does set the wrong path right now and users are therefore needed to manually fixing the PATH after installing a program like e.g. `webdev` through pub.

**Comment by sortie** [comment]
Done in 7f5b6d7ceaaae52784dd10ccfbcb71d0d37b4d08
